spring:
  datasource:
    test1:
      driverClassName: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@192.168.1.49:1521:ejpt
      username: tzzf
      password: tzzf
    test2:
      driverClassName: oracle.jdbc.driver.OracleDriver
      jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:JCSD
      username: tzzf
      password: tzzf


jurl: http://localhost:8080/hehe

url: http://localhost:8083/order
server:
  port: 8088
  tomcat:
    max-connections: 2000
    max-threads: 1000


logging:
  config: classpath:logback.xml


